scan_timeout = 60
add_newline = false

[username]
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
disabled = false
format = "[$hostname]($style) "

[localip]
ssh_only = true
disabled = false
format = "[$localipv4]($style) "

[line_break]
disabled = false

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[nodejs]
format = "[$symbol($version )]($style)"

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "
