# Yazi keymap configuration
# Official docs: https://yazi-rs.github.io/docs/configuration/keymap

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
